theme: jekyll-theme-cayman
title: Encoding in Style\: A StyleGAN Encoder for Image-to-Image Translation
description: Elad Richardson, Yuval Alaluf, Or Patashnik, Yotam Nitzan, Yaniv Azar, Stav Shapiro, Daniel Cohen-Or
